@extends('layout') 

@section('page')
<div class="container-fluid" style="padding: 50vh 0px;">
 	<div class="col-lg-12" style="padding: 30px 100px; text-align: center;">
 		<img style="width:80%" src="{{asset('media/404-1.jpg')}}"/>
 		<h2>El producto que estás buscando ya no está disponible.</h2>
 		<div>  
 			<a href="">
 				<h3>Buscar un producto similar similar</h3>
 			</a>
 		</div>
 	</div> 
 	  
 @endsection 